import type { Article, State } from './types';
export const categories = [
  {slug:'politique', name:'Politique', description:'Les décisions qui façonnent notre avenir.', icon:'01'},
  {slug:'economie', name:'Économie', description:'Décrypter les mutations et les opportunités.', icon:'02'},
  {slug:'societe', name:'Société', description:'Les histoires qui nous ressemblent.', icon:'03'},
  {slug:'culture', name:'Culture', description:'La création dans toute sa diversité.', icon:'04'},
  {slug:'sport', name:'Sport', description:'La passion qui nous rassemble.', icon:'05'},
  {slug:'international', name:'International', description:'Le Sénégal ouvert sur le monde.', icon:'06'},
  {slug:'technologie', name:'Technologie', description:'Les idées qui dessinent demain.', icon:'07'},
  {slug:'environnement', name:'Environnement', description:'Protéger notre terre et nos océans.', icon:'08'},
];
const stories: [string,string,string,string,string,string][] = [
 ['Le Sénégal de demain se construit aujourd’hui','politique','Entre nouvelles ambitions et attentes citoyennes, le pays écrit une nouvelle page de son histoire.','dakar-coast','Awa Diop','Le changement ne se décrète pas : il se construit, jour après jour, dans les villes comme dans les campagnes. Au Sénégal, les conversations sur l’avenir du pays prennent une ampleur nouvelle.\n\nDes initiatives locales aux grandes orientations nationales, une même question traverse le débat public : comment faire des promesses d’aujourd’hui des réalités de demain ? La réponse tient autant à la qualité des institutions qu’à l’énergie de celles et ceux qui font vivre le pays.\n\nSur le terrain, les attentes sont concrètes. Emploi, éducation, accès aux services et transparence figurent parmi les priorités exprimées par les citoyens. Une transformation durable demandera du temps, de l’écoute et une volonté collective.'],
 ['À Dakar, une génération invente l’économie de demain','economie','Entrepreneuriat, nouvelles idées et audace : portrait d’une jeunesse qui refuse d’attendre.','youth','Mamadou Fall','Dans les espaces de travail partagés de Dakar, les idées circulent à toute vitesse. Des équipes imaginent des solutions adaptées aux réalités locales, de la finance à l’agriculture.\n\nLeur ambition dépasse les frontières de la capitale. Pour ces entrepreneurs, innover signifie avant tout répondre à des besoins réels, avec des outils accessibles et une connaissance fine du terrain.\n\nLes obstacles restent nombreux : financement, formation, infrastructures. Mais la détermination de cette génération dessine déjà de nouvelles perspectives pour l’économie sénégalaise.'],
 ['Sur la côte, les pêcheurs face à un océan qui change','environnement','À Saint-Louis, la mer nourrit des familles depuis des générations. Aujourd’hui, son équilibre vacille.','fishing','Fatou Ndiaye','À l’aube, les pirogues retrouvent l’Atlantique. Le geste est ancien, transmis de génération en génération, mais les conditions ont changé.\n\nLa raréfaction de certaines ressources et l’érosion côtière bouleversent les habitudes. Les communautés s’organisent pour préserver leur activité et imaginer une gestion plus durable de la mer.\n\nLeur parole rappelle une évidence : protéger l’océan, c’est aussi protéger celles et ceux qui en vivent.'],
 ['Dans les marchés de Dakar, le pouls d’une ville','societe','Au rythme des étals et des rencontres, les marchés racontent le quotidien d’une capitale en mouvement.','market','Awa Diop','Il suffit de traverser les allées d’un marché dakarois pour entendre battre le cœur de la ville. Les vendeuses interpellent les habitués, les couleurs se répondent, les conversations s’entrecroisent.\n\nDerrière cette vitalité, il y a des parcours de travail, de solidarité et d’adaptation. Les marchés sont des lieux de commerce, mais aussi de transmission et de lien social.\n\nÀ l’heure où la capitale change rapidement, ces espaces demeurent des repères essentiels de la vie quotidienne.'],
 ['Le football de quartier, une école de vie','sport','Bien plus qu’un jeu, le football rassemble les jeunes et fait vivre les quartiers.','sport','Ibrahima Sarr','Sur un terrain de sable, quelques plots suffisent pour dessiner les limites du jeu. Les équipes se forment, les voisins s’arrêtent pour regarder, et le quartier trouve un langage commun.\n\nCes rencontres sont aussi des lieux d’apprentissage : respect, collectif et persévérance se cultivent au fil des matchs. Pour beaucoup de jeunes, le sport est une respiration et un horizon.\n\nDes bénévoles et associations travaillent à leur donner davantage de moyens, convaincus que le talent grandit là où on lui fait de la place.'],
 ['La ville se réinvente : un autre regard sur Dakar','culture','Architecture, espaces publics et imagination : les nouveaux visages de la capitale.','architecture','Ndeye Mbaye','Dakar se raconte aussi par ses bâtiments, ses rues et ses places. À chaque coin de rue, une autre façon d’habiter la ville apparaît.\n\nArchitectes, artistes et habitants questionnent ensemble la place du patrimoine et celle de l’innovation. L’enjeu : créer des espaces ouverts, vivants et accessibles à tous.\n\nCette créativité urbaine fait de la capitale un laboratoire d’idées, à la croisée des héritages et des futurs possibles.'],
 ['L’innovation locale à la conquête de nouveaux horizons','technologie','De jeunes talents créent des outils pensés ici, pour résoudre des défis d’ici et d’ailleurs.','youth','Mamadou Fall','L’innovation n’a pas d’adresse unique. À Dakar, les projets technologiques naissent souvent d’un problème très concret et d’une envie de faire mieux.\n\nSanté, agriculture, éducation : les pistes explorées sont nombreuses. Leur point commun est une attention aux usages et aux personnes.\n\nPour faire grandir cet écosystème, l’accès aux compétences et au financement reste décisif. Mais l’élan est déjà là.'],
 ['Sénégal et Afrique de l’Ouest : des liens à réinventer','international','Commerce, mobilité, culture : une région qui partage plus qu’une frontière.','dakar-coast','Cheikh Ba','L’Afrique de l’Ouest est faite de circulations anciennes. Les échanges humains et économiques dessinent un espace commun, bien au-delà des cartes.\n\nFace aux défis contemporains, la coopération régionale retrouve une place centrale. Les solutions durables demanderont dialogue, confiance et initiatives partagées.\n\nLe Sénégal y occupe une position singulière, tourné à la fois vers ses voisins et vers le monde.'],
 ['Les voix qui font vibrer la nouvelle scène culturelle','culture','Musique, arts visuels et nouvelles écritures : rencontre avec une génération créative.','music','Ndeye Mbaye','La scène culturelle sénégalaise déborde d’énergie. Dans les ateliers, les salles et les espaces indépendants, de nouvelles voix s’affirment.\n\nElles puisent dans les traditions sans s’y enfermer, multiplient les collaborations et inventent leurs propres formes. Leur travail raconte un pays pluriel et ouvert.\n\nSoutenir ces talents, c’est donner toute sa place à la culture dans notre avenir collectif.'],
 ['Agriculture : cultiver autrement pour durer','economie','Face aux défis climatiques, des producteurs expérimentent des pratiques plus résilientes.','agriculture','Fatou Ndiaye','Dans les campagnes, les agriculteurs ajustent leurs pratiques au rythme des saisons. L’eau, les sols et l’accès aux marchés sont au cœur de leurs préoccupations.\n\nDes solutions locales émergent, portées par l’expérience des producteurs et le partage des savoirs. Leur force réside dans leur adaptation au territoire.\n\nL’avenir de l’agriculture se joue aussi dans la reconnaissance de celles et ceux qui nourrissent le pays.'],
 ['Éducation : les parcours qui ouvrent des portes','societe','En ville comme en région, apprendre reste la clé d’un avenir choisi.','youth','Awa Diop','Dans chaque salle de classe, il y a des rêves et des trajectoires en devenir. L’éducation donne des outils pour comprendre le monde et y prendre sa place.\n\nL’accès à un enseignement de qualité demeure cependant inégal. Enseignants, familles et associations cherchent ensemble des réponses concrètes.\n\nInvestir dans l’apprentissage, c’est investir dans toute une génération.'],
 ['Protéger le littoral, préserver notre avenir','environnement','L’érosion côtière interroge la façon de vivre avec l’Atlantique.','fishing','Fatou Ndiaye','Sur le littoral, la mer avance et transforme les paysages. Pour les habitants, la question n’est pas abstraite : elle touche les maisons, les métiers et les souvenirs.\n\nLa protection des côtes exige de croiser sciences, décisions publiques et connaissances locales. Aucune réponse unique ne suffira.\n\nÉcouter les communautés concernées est le premier pas vers des solutions durables.'],
 ['Quand le sport féminin prend toute sa place','sport','Des athlètes et des collectifs ouvrent la voie à une pratique plus inclusive.','sport','Ibrahima Sarr','Sur les terrains, les sportives sénégalaises écrivent leur propre histoire. Leurs performances suscitent l’admiration et inspirent les plus jeunes.\n\nMais l’accès aux infrastructures et à la visibilité reste un défi. Clubs et associations multiplient les initiatives pour changer la donne.\n\nChaque match gagné est aussi une victoire pour la place des femmes dans le sport.'],
 ['Les nouvelles routes du commerce africain','international','Les échanges se transforment à l’échelle du continent, avec de nouvelles perspectives.','architecture','Cheikh Ba','Sur le continent, les échanges commerciaux ouvrent des perspectives inédites. Entrepreneurs et institutions cherchent à rapprocher les marchés.\n\nLes défis logistiques et réglementaires persistent, mais les collaborations progressent. Pour les acteurs locaux, l’enjeu est de transformer ces dynamiques en opportunités concrètes.\n\nUne économie plus connectée se construit pas à pas, à l’échelle de la région.'],
 ['Numérique : rendre la technologie accessible à tous','technologie','La fracture numérique appelle des réponses au plus près des usages.','youth','Mamadou Fall','Un accès à internet ne suffit pas toujours. Comprendre les outils, pouvoir les utiliser et y trouver sa place sont tout aussi importants.\n\nDes initiatives de formation proposent une approche pratique, adaptée aux besoins des publics. Leur succès repose sur la proximité et la confiance.\n\nUn numérique inclusif est un numérique qui n’oublie personne.'],
 ['Au cœur des quartiers, la force du collectif','societe','Associations et voisins tissent chaque jour des solidarités concrètes.','community','Awa Diop','Dans les quartiers, l’entraide prend mille formes. Un projet commun, une activité partagée, un coup de main au bon moment : ces gestes font la différence.\n\nLes associations locales connaissent les réalités du terrain et savent mobiliser les énergies. Leur travail discret change des vies.\n\nRaconter ces histoires, c’est rappeler que le collectif reste une ressource précieuse.'],

 ['Le patrimoine de Saint-Louis entre mémoire et avenir','culture','Une ville historique cherche à préserver son âme tout en se réinventant.','architecture','Ndeye Mbaye','À Saint-Louis, les façades anciennes portent la mémoire de plusieurs générations. Les rues témoignent d’une histoire riche et complexe.\n\nPréserver ce patrimoine ne signifie pas figer la ville. Habitants, artisans et acteurs culturels imaginent des usages qui lui donnent une nouvelle vie.\n\nL’avenir de Saint-Louis se construit dans ce dialogue patient entre mémoire et mouvement.'],
 ['Les femmes qui font avancer l’économie locale','economie','Commerce, agriculture, artisanat : des initiatives transforment les territoires.','market','Marième Diallo','Partout au Sénégal, des femmes entreprennent et inventent des modèles économiques ancrés dans leurs communautés.\n\nLeur savoir-faire crée des emplois et renforce les réseaux locaux. Derrière chaque activité, il y a une histoire d’audace et de persévérance.\n\nMieux accompagner ces initiatives est une opportunité pour l’ensemble du pays.'],
 ['La langue comme lien entre les générations','societe','Wolof, pulaar, sérère et tant d’autres : les mots transmettent bien plus que des idées.','community','Awa Diop','Les langues vivent dans les conversations du quotidien, les chansons et les histoires racontées le soir. Elles relient les générations.\n\nLeur diversité est une richesse, mais aussi un défi pour l’éducation et la transmission. De nombreuses initiatives explorent de nouvelles façons de les faire vivre.\n\nAccueillir toutes ces voix, c’est reconnaître la pluralité du Sénégal.'],
 ['Au rythme du mbalax : la musique qui rassemble','culture','Des scènes de quartier aux grandes salles, les sons du Sénégal continuent de voyager.','music','Ndeye Mbaye','Le rythme résonne et la foule répond. La musique sénégalaise est un langage partagé, capable de traverser les frontières.\n\nUne nouvelle génération d’artistes dialogue avec cet héritage en inventant ses propres sonorités. La création se nourrit de rencontres et d’expérimentations.\n\nSur scène comme dans les studios, le Sénégal affirme une voix singulière.'],
 ['Énergie solaire : une promesse pour les territoires','environnement','La transition énergétique prend forme au plus près des besoins.','agriculture','Ousmane Faye','Sous le soleil sénégalais, de nouveaux projets énergétiques émergent. Ils cherchent à répondre aux besoins des communautés avec des ressources locales.\n\nL’accès à une énergie fiable peut changer le quotidien des familles, des écoles et des petites entreprises. Mais les solutions doivent rester accessibles et durables.\n\nLa transition se mesure à ses effets concrets sur la vie des gens.'],
 ['Entre mer et ville, Dakar cherche son équilibre','environnement','L’urbanisation rapide interroge la place de la nature dans la capitale.','dakar-coast','Ousmane Faye','Dakar grandit, se densifie et se transforme. La ville cherche des espaces pour respirer, tandis que l’océan rappelle sa présence constante.\n\nUrbanistes et habitants réfléchissent à des aménagements plus attentifs à l’environnement et aux usages quotidiens. Les choix d’aujourd’hui dessineront la ville de demain.\n\nPenser la capitale à hauteur humaine est une ambition collective.'],
 ['Basketball : la relève entre dans le jeu','sport','Dans les clubs et les écoles, de jeunes talents travaillent leurs rêves.','sport','Ibrahima Sarr','Sur le parquet, chaque entraînement compte. Les jeunes basketteurs apprennent à jouer ensemble, à progresser et à croire en leurs possibilités.\n\nLes entraîneurs bénévoles jouent un rôle essentiel, souvent avec peu de moyens. Leur engagement ouvre des perspectives bien au-delà du terrain.\n\nLa relève grandit grâce à ceux qui lui font confiance.'],
 ['Quand la diaspora investit dans les idées d’ici','international','Les échanges humains nourrissent de nouveaux projets entre le Sénégal et le monde.','youth','Cheikh Ba','De Dakar à Paris, de Thiès à Montréal, les liens de la diaspora traversent les frontières. Ils prennent la forme de projets, de savoirs partagés et d’engagements.\n\nAu-delà des transferts financiers, les échanges de compétences et d’expériences offrent de nouvelles pistes pour les territoires.\n\nCes connexions racontent un Sénégal présent partout où vivent ses communautés.'],
 ['Santé de proximité : aller au-devant des besoins','societe','Des acteurs locaux travaillent à rapprocher les soins des habitants.','community','Marième Diallo','Accéder aux soins devrait être simple, où que l’on vive. Dans la réalité, la distance et les moyens disponibles créent encore des obstacles.\n\nProfessionnels et associations développent des réponses de proximité, fondées sur l’écoute et la prévention. Leur action est souvent discrète mais déterminante.\n\nUne santé accessible commence par la connaissance du terrain.'],
 ['Le tourisme à la rencontre des territoires','economie','Voyager autrement, découvrir les savoir-faire et soutenir les communautés.','fishing','Marième Diallo','Le Sénégal offre une diversité de paysages, d’histoires et de rencontres. Des initiatives proposent de les découvrir en prenant le temps.\n\nCe tourisme plus attentif valorise les guides, les artisans et les producteurs locaux. Il pose aussi la question de la préservation des lieux.\n\nLe voyage devient alors un échange, plutôt qu’une simple étape.'],
 ['Apprendre à coder, imaginer sa place','technologie','La formation au numérique ouvre de nouveaux chemins pour les jeunes.','youth','Mamadou Fall','Dans un atelier, les premiers programmes prennent forme sur les écrans. Pour les participants, apprendre à coder, c’est aussi apprendre à résoudre des problèmes.\n\nLes formations de proximité permettent de découvrir des métiers et de développer la confiance en soi. La curiosité y compte autant que la technique.\n\nRendre ces savoirs accessibles peut élargir les horizons d’une génération.'],
 ['La photographie, mémoire vivante du Sénégal','culture','Des photographes racontent le pays avec sensibilité et liberté.','community','Ndeye Mbaye','Une image arrête le temps, mais elle peut aussi ouvrir une conversation. Les photographes sénégalais explorent les visages du présent et les traces du passé.\n\nLeur regard interroge ce que l’on choisit de montrer et ce que l’on oublie parfois de voir. Expositions et projets collectifs donnent à ces œuvres une place nouvelle.\n\nLa photographie devient un outil de mémoire et de dialogue.'],
 ['Les communes au défi de la participation citoyenne','politique','Comment donner aux habitants une place réelle dans les décisions locales ?','architecture','Awa Diop','À l’échelle des communes, les décisions publiques touchent directement la vie quotidienne. Voirie, écoles, espaces de rencontre : les enjeux sont proches.\n\nDes démarches de concertation cherchent à associer davantage les habitants. Leur réussite dépend de la transparence et de la continuité du dialogue.\n\nLa participation ne se limite pas à être consulté : elle suppose de pouvoir être entendu.'],
 ['L’artisanat sénégalais trouve de nouveaux marchés','economie','Entre gestes hérités et outils numériques, les savoir-faire se réinventent.','market','Marième Diallo','Dans les ateliers, la précision des gestes raconte des années de transmission. Textile, bois, métal : chaque pièce porte une histoire.\n\nDe nouveaux canaux de vente permettent aux artisans de rencontrer d’autres publics. Mais grandir sans perdre la qualité et le sens du travail reste un défi.\n\nL’avenir de l’artisanat s’écrit entre héritage et invention.'],
 ['Face aux pluies, bâtir des villes plus résilientes','environnement','Anticiper les risques et adapter les quartiers devient une priorité.','architecture','Ousmane Faye','Quand arrivent les fortes pluies, certains quartiers se retrouvent particulièrement exposés. La question de l’aménagement devient alors très concrète.\n\nDes réponses existent : entretenir les infrastructures, mieux connaître les sols et associer les habitants aux décisions. L’adaptation demande une vision de long terme.\n\nUne ville résiliente est une ville qui protège ses habitants.']
];
export const seedState: State = {
 articles: stories.map((s,i): Article => ({id:`article-${i+1}`,slug:s[0].toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:s[0],category:s[1],excerpt:s[2],image:`/images/${s[3]}.jpg`,author:s[4],body:s[5],publishedAt:new Date(Date.UTC(2026,8,30-i,9,15)).toISOString(),readingTime:Math.max(3,Math.ceil(s[5].length/500)),featured:i<3,status:'published'})),
 journalists:[
  {id:'j1',name:'Awa Diop',role:'Rédactrice en chef',bio:'Passionnée par les récits de société et la vie publique sénégalaise.',initials:'AD'},
  {id:'j2',name:'Mamadou Fall',role:'Économie & innovation',bio:'Observe les transformations économiques et les nouvelles idées.',initials:'MF'},
  {id:'j3',name:'Fatou Ndiaye',role:'Environnement',bio:'Raconte les territoires, le littoral et celles et ceux qui les habitent.',initials:'FN'},
  {id:'j4',name:'Ndeye Mbaye',role:'Culture',bio:'Explore la création contemporaine et les scènes culturelles.',initials:'NM'},
  {id:'j5',name:'Ibrahima Sarr',role:'Sports',bio:'Suit le sport de proximité comme les grandes compétitions.',initials:'IS'},
  {id:'j6',name:'Cheikh Ba',role:'International',bio:'Décrypte les enjeux régionaux et les échanges africains.',initials:'CB'},
  {id:'j7',name:'Marième Diallo',role:'Économie & société',bio:'Suit les initiatives locales et les parcours entrepreneuriaux.',initials:'MD'},
  {id:'j8',name:'Ousmane Faye',role:'Climat & territoires',bio:'Explore les défis environnementaux et les réponses du terrain.',initials:'OF'},
  {id:'j9',name:'Sokhna Kane',role:'Reportages',bio:'Prend le temps de raconter les histoires humaines du pays.',initials:'SK'},
 ],comments:[],subscribers:[],messages:[],users:[]
};
export const podcasts = [
 {title:'Le Grand Décryptage',tag:'Actualité',description:'Les faits, le contexte, les perspectives. Une autre façon de comprendre l’actualité.',duration:'28 min',color:'orange'},
 {title:'Voix de Dakar',tag:'Société',description:'Des histoires singulières pour raconter le Sénégal d’aujourd’hui.',duration:'35 min',color:'blue'},
 {title:'Demain, ici',tag:'Innovation',description:'Celles et ceux qui imaginent les solutions de demain.',duration:'24 min',color:'green'},
 {title:'Culture en mouvement',tag:'Culture',description:'Rencontres avec les artistes et créateurs qui font vibrer la scène.',duration:'31 min',color:'purple'},
 {title:'Terrain libre',tag:'Sport',description:'Au plus près des athlètes, des clubs et des supporters.',duration:'26 min',color:'red'},
 {title:'Horizons africains',tag:'International',description:'Le continent en conversations, en idées et en perspectives.',duration:'33 min',color:'yellow'},
];
export const formatDate = (date: string) => new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date));
export const categoryName = (slug: string) => categories.find(c=>c.slug===slug)?.name ?? slug;
