import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { getState } from '@/lib/store';
import { categoryName, formatDate } from '@/lib/content';
import { ArticleCard, ReadingMeta, SectionHeading } from '@/components/Editorial';
import { CommentBox, ShareButtons } from '@/components/Forms';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const {articles}=await getState();const a=articles.find(a=>a.slug===slug&&a.status==='published');if(!a)return {title:'Article introuvable'};return {title:a.title,description:a.excerpt,openGraph:{title:a.title,description:a.excerpt,type:'article',publishedTime:a.publishedAt,images:[a.image]}};}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const state=await getState();const a=state.articles.find(a=>a.slug===slug&&a.status==='published');if(!a)notFound();const comments=state.comments.filter(c=>c.articleId===a.id&&c.approved);const related=state.articles.filter(x=>x.id!==a.id&&x.category===a.category&&x.status==='published').slice(0,3);const journalist=state.journalists.find(j=>j.name===a.author);const base=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';const jsonLd={'@context':'https://schema.org','@type':'NewsArticle',headline:a.title,description:a.excerpt,image:[new URL(a.image,base).toString()],datePublished:a.publishedAt,dateModified:a.publishedAt,author:{'@type':'Person',name:a.author},publisher:{'@type':'Organization',name:'SENCOURRIER',url:base},mainEntityOfPage:new URL(`/article/${a.slug}`,base).toString()};return <>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,'\\u003c')}}/>
 <div className="container"><header className="article-header"><div className="breadcrumb"><Link href="/">Accueil</Link><span>→</span><Link href={`/rubrique/${a.category}`}>{categoryName(a.category)}</Link><span>→</span> Article</div><Link href={`/rubrique/${a.category}`} className="category-label">{categoryName(a.category)} / DÉCRYPTAGE</Link><h1>{a.title}</h1><p className="standfirst">{a.excerpt}</p><div className="article-byline"><span className="author-avatar">{journalist?.initials||a.author.slice(0,2).toUpperCase()}</span><span>Par <strong>{a.author}</strong></span></div><ReadingMeta article={a}/></header><div className="article-hero-image"><Image src={a.image} alt={a.title} fill priority sizes="(max-width: 1360px) 100vw, 1360px"/></div><p className="container" style={{color:"var(--muted)",fontSize:10,marginTop:10}}>Image d’illustration générée, sans lien avec un événement précis.</p><div className="article-body-wrap"><aside className="article-sidebar"><ShareButtons title={a.title}/></aside><div className="article-content">{a.body.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div><div/></div><div className="article-end"><div className="tags"><Link href={`/rubrique/${a.category}`}># {categoryName(a.category)}</Link><Link href="/"># Sénégal</Link></div><p style={{color:'var(--muted)',fontSize:11,marginTop:25}}>Publié le {formatDate(a.publishedAt)} · SENCOURRIER</p></div><div className="comment-area"><h2>La conversation</h2>{comments.length?comments.map(c=><div className="published-comment" key={c.id}><strong>{c.name}</strong><time>{formatDate(c.createdAt)}</time><p>{c.body}</p></div>):<p style={{color:'var(--muted)',fontSize:14}}>Soyez la première personne à réagir à cet article.</p>}<CommentBox articleId={a.id}/></div></div>{related.length>0&&<section className="container section-block related-section"><SectionHeading kicker="À DÉCOUVRIR AUSSI" title="Pour aller plus loin" href={`/rubrique/${a.category}`} linkText="Voir la rubrique"/><div className="three-grid">{related.map(r=><ArticleCard article={r} key={r.id}/>)}</div></section>}</>}
