import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, Play, Radio, Headphones, MoveUpRight } from 'lucide-react';
import { getState } from '@/lib/store';
import { categories, formatDate } from '@/lib/content';
import { FeaturedStory, ArticleCard, Eyebrow, SectionHeading, StoryRow } from '@/components/Editorial';
import { NewsletterForm } from '@/components/Forms';
export const dynamic='force-dynamic';
export default async function Home(){const {articles}=await getState();const published=articles.filter(a=>a.status==='published').sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));const [hero,...rest]=published; if(!hero)return <div className="container empty-state"><h1>Bienvenue sur SENCOURRIER</h1><p>Les premiers articles arrivent bientôt.</p></div>;
 return <>
 <div className="container home-intro"><div className="home-intro-left"><span className="orange-bar"/> LE MÉDIA DE CEUX QUI REGARDENT PLUS LOIN</div><div className="home-intro-right">L’ACTUALITÉ DU SÉNÉGAL, AUTREMENT. <span>✳</span></div></div>
 <section className="container lead-grid"><FeaturedStory article={hero}/><div className="lead-side"><div className="side-heading"><span>EN CE MOMENT</span><span>01 — 03</span></div>{rest.slice(0,2).map(a=><article className="side-story" key={a.id}><Link href={`/article/${a.slug}`} className="side-image"><Image src={a.image} alt="" fill sizes="(max-width: 800px) 100vw, 300px"/></Link><div className="side-story-body"><Link href={`/rubrique/${a.category}`} className="category-label">{categories.find(c=>c.slug===a.category)?.name}</Link><h2><Link href={`/article/${a.slug}`}>{a.title}</Link></h2><p>{a.excerpt}</p><span>{formatDate(a.publishedAt)}</span></div></article>)}<Link href="/recherche" className="side-more">TOUTE L’ACTUALITÉ <ArrowUpRight size={17}/></Link></div></section>
 <div className="container ticker"><span className="ticker-label">LE REGARD SENCOURRIER</span><span>Des faits. Des voix. Des perspectives.</span><span className="ticker-star">✳</span><span>Pour comprendre le Sénégal qui bouge.</span></div>
 <section className="container section-block"><SectionHeading kicker="L’ESSENTIEL" title="À lire aujourd’hui" href="/recherche" linkText="Tous les articles"/><div className="three-grid">{rest.slice(2,5).map(a=><ArticleCard key={a.id} article={a}/>)}</div></section>
 <section className="spotlight"><div className="container spotlight-grid"><div className="spotlight-copy"><Eyebrow>GRAND ANGLE / SOCIÉTÉ</Eyebrow><h2>Des histoires d’ici.<br/><em>Un écho partout.</em></h2><p>Nous croyons aux récits qui prennent le temps. À celles et ceux qui font le Sénégal, loin des raccourcis et au plus près du réel.</p><Link href="/a-propos" className="button button-light">Découvrir notre regard <ArrowUpRight size={18}/></Link><span className="spotlight-index">S. / 001</span></div><div className="spotlight-image"><Image src="/images/market.jpg" alt="Scène de marché à Dakar" fill sizes="(max-width: 800px) 100vw, 50vw"/></div></div></section>
 <section className="container section-block latest-section"><div className="latest-main"><SectionHeading kicker="LE FIL" title="Les dernières histoires" href="/recherche" linkText="Voir tout"/><div className="story-list">{rest.slice(5,10).map((a,i)=><StoryRow key={a.id} article={a} index={i+1}/>)}</div></div><aside className="latest-aside"><div className="aside-box"><span className="aside-deco">✳</span><Eyebrow>RESTEZ INFORMÉS</Eyebrow><h3>Le meilleur du Sénégal, dans votre boîte mail.</h3><p>Une sélection de nos histoires et analyses. Chaque semaine, directement chez vous.</p><NewsletterForm/><small>Gratuit. Sans bruit. Désinscription à tout moment.</small></div><div className="aside-quote"><span>“</span><p>Une information qui regarde le pays avec exigence et optimisme.</p><strong>LA PROMESSE SENCOURRIER</strong></div></aside></section>
 <section className="container section-block"><SectionHeading kicker="EXPLORER" title="À chaque sujet, son regard"/><div className="category-grid">{categories.map((c,i)=><Link href={`/rubrique/${c.slug}`} className="category-tile" key={c.slug}><span className="tile-num">{c.icon} / 08</span><span className="tile-icon">{['◈','↗','◎','✳','◉','⌁','⬡','☼'][i]}</span><h3>{c.name}</h3><p>{c.description}</p><ArrowUpRight size={20} className="tile-arrow"/></Link>)}</div></section>
 <section className="container section-block media-section"><SectionHeading kicker="À VOIR & À ÉCOUTER" title="L’info sous un autre angle"/><div className="media-grid"><Link href="/tv" className="media-tile media-tv"><Image src="/images/dakar-coast.jpg" alt="" fill sizes="(max-width: 800px) 100vw, 50vw"/><div className="media-shade"/><div className="media-content"><span className="media-kicker"><Radio size={15}/> SENCOURRIER TV</span><div className="media-bottom"><div><h3>Les images racontent<br/>aussi l’histoire.</h3><span>Découvrir la TV <ArrowRight size={15}/></span></div><span className="media-play"><Play size={22} fill="currentColor"/></span></div></div></Link><Link href="/podcasts" className="media-tile media-podcast"><div className="podcast-art"><span className="podcast-ring ring-one"/><span className="podcast-ring ring-two"/><span className="podcast-ring ring-three"/><Headphones size={70} strokeWidth={1.1}/></div><div className="media-content"><span className="media-kicker"><Headphones size={15}/> LES PODCASTS</span><div className="media-bottom"><div><h3>Des voix pour<br/>aller plus loin.</h3><span>Tout écouter <ArrowRight size={15}/></span></div><span className="media-play"><MoveUpRight size={24}/></span></div></div></Link></div></section>
 <section className="bottom-newsletter"><div className="container bottom-newsletter-inner"><div><Eyebrow>LA NEWSLETTER</Eyebrow><h2>Gardez un temps<br/>d’avance.</h2><p>L’essentiel de l’actualité sénégalaise, des histoires qui inspirent et un regard qui fait la différence.</p></div><div className="bottom-form"><NewsletterForm dark/><span>REJOIGNEZ LES LECTEURS QUI VOIENT PLUS LOIN. <ArrowRight size={14}/></span></div></div></section>
 </>}
