'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, Download, FileText, LayoutDashboard, Mail, MessageCircle, PenLine, Plus, Trash2, Users, X } from 'lucide-react';
import { categories } from '@/lib/content';
import type { State, Article } from '@/lib/types';
type Tab='overview'|'articles'|'journalists'|'users'|'comments'|'subscribers'|'messages';
const tabs:{id:Tab,label:string,icon:typeof FileText}[]=[{id:'overview',label:'Vue d’ensemble',icon:LayoutDashboard},{id:'articles',label:'Articles',icon:FileText},{id:'journalists',label:'Journalistes',icon:PenLine},{id:'users',label:'Utilisateurs',icon:Users},{id:'comments',label:'Commentaires',icon:MessageCircle},{id:'subscribers',label:'Abonnés',icon:Mail},{id:'messages',label:'Messages',icon:Mail}];
const empty:State={articles:[],journalists:[],users:[],comments:[],subscribers:[],messages:[]};
export default function AdminDashboard({protectedAdmin}:{protectedAdmin:boolean}){
 const [state,setState]=useState<State>(empty),[tab,setTab]=useState<Tab>('overview'),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[form,setForm]=useState<'article'|'journalist'|'user'|null>(null),[editing,setEditing]=useState<Article|null>(null),[saving,setSaving]=useState(false);
 const refresh=useCallback(async()=>{try{const data=await Promise.all((['articles','journalists','users','comments','subscribers','messages'] as const).map(async key=>{const res=await fetch(`/api/admin/${key}`,{cache:'no-store'});if(!res.ok)throw new Error('Impossible de charger les données.');return [key,await res.json()] as const}));setState(Object.fromEntries(data) as State);}catch(e){setNotice((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh()},[refresh]);
 async function request(resource:string,method:string,body?:object,id?:string){setSaving(true);setNotice('');try{const res=await fetch(`/api/admin/${resource}${method==='DELETE'?`?id=${encodeURIComponent(id||'')}`:''}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await res.json();if(!res.ok)throw new Error(result.error||'Une erreur est survenue.');await refresh();setForm(null);setEditing(null);setNotice(method==='DELETE'?'Élément supprimé.':'Modifications enregistrées.');}catch(e){setNotice((e as Error).message)}finally{setSaving(false)}}
 function submit(e:FormEvent<HTMLFormElement>,resource:string){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(editing&&resource==='articles')request(resource,'PATCH',{...data,id:editing.id});else request(resource,'POST',data);}
 function remove(resource:string,id:string){if(confirm('Supprimer cet élément définitivement ?'))request(resource,'DELETE',undefined,id)}
 const unpublished=state.articles.filter(a=>a.status==='draft').length;const pending=state.comments.filter(c=>!c.approved).length;
 return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>S.</span> SENCOURRIER <small>RÉDACTION</small></Link><div className="admin-nav-label">ESPACE DE TRAVAIL</div><nav>{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} onClick={()=>{setTab(t.id);setForm(null);setEditing(null)}} className={tab===t.id?'selected':''}><Icon size={18}/>{t.label}{t.id==='comments'&&pending>0&&<b>{pending}</b>}</button>})}</nav><Link href="/" className="admin-back"><ArrowLeft size={16}/> Retour au site</Link></aside><main className="admin-main"><div className="admin-top"><span>SENCOURRIER <b>/</b> ESPACE RÉDACTION <b>/</b> {tabs.find(t=>t.id===tab)?.label.toUpperCase()}</span><span className="admin-top-live"><i/> ESPACE RÉDACTION</span></div><div className="admin-body">{!protectedAdmin&&<div className="admin-warning"><strong>Attention :</strong> l’espace rédaction est ouvert sans authentification. Définissez <code>ADMIN_PASSWORD</code> avant toute mise en ligne publique.</div>}{notice&&<div className="admin-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fermer"><X size={16}/></button></div>}{loading?<p>Chargement de la rédaction…</p>:<>
 {tab==='overview'&&<><div className="admin-heading"><div><span className="admin-kicker">TABLEAU DE BORD / 01</span><h1>Bonjour, la rédaction<span>.</span></h1><p>Votre espace pour raconter le Sénégal, autrement.</p></div><button className="admin-primary" onClick={()=>{setTab('articles');setForm('article')}}><Plus size={17}/> Nouvel article</button></div><div className="admin-stats"><div><FileText size={21}/><strong>{state.articles.length}</strong><span>ARTICLES</span><small>{unpublished} brouillon{unpublished>1?'s':''}</small></div><div><Users size={21}/><strong>{state.journalists.length}</strong><span>JOURNALISTES</span><small>Dans la rédaction</small></div><div><MessageCircle size={21}/><strong>{state.comments.length}</strong><span>COMMENTAIRES</span><small>{pending} en attente</small></div><div><Mail size={21}/><strong>{state.subscribers.length}</strong><span>ABONNÉS</span><small>À la newsletter</small></div></div><div className="admin-section-head"><h2>Articles récents</h2><button onClick={()=>setTab('articles')}>Voir tous les articles <ArrowRight size={16}/></button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ARTICLE</th><th>RUBRIQUE</th><th>STATUT</th><th>DATE</th></tr></thead><tbody>{state.articles.slice(0,6).map(a=><tr key={a.id}><td><strong>{a.title}</strong></td><td>{categories.find(c=>c.slug===a.category)?.name||a.category}</td><td><span className={`status-pill ${a.status}`}>{a.status==='published'?'Publié':'Brouillon'}</span></td><td>{new Date(a.publishedAt).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div></>}
 {tab==='articles'&&<><div className="admin-heading"><div><span className="admin-kicker">CONTENU / ARTICLES</span><h1>Les articles<span>.</span></h1><p>Écrivez, publiez et gérez vos histoires.</p></div><button className="admin-primary" onClick={()=>{setEditing(null);setForm('article')}}><Plus size={17}/> Nouvel article</button></div>{form==='article'?<div className="admin-form-panel"><div className="admin-section-head"><h2>{editing?'Modifier l’article':'Nouvel article'}</h2><button onClick={()=>{setForm(null);setEditing(null)}}><X size={17}/> Fermer</button></div><form onSubmit={e=>submit(e,'articles')} className="admin-form"><label>Titre<input name="title" required defaultValue={editing?.title} placeholder="Le titre de votre article"/></label><div className="admin-form-grid"><label>Rubrique<select name="category" required defaultValue={editing?.category||categories[0].slug}>{categories.map(c=><option value={c.slug} key={c.slug}>{c.name}</option>)}</select></label><label>Auteur<input name="author" required defaultValue={editing?.author} placeholder="Nom de l’auteur"/></label></div><label>Résumé<textarea name="excerpt" required rows={3} defaultValue={editing?.excerpt} placeholder="Quelques lignes pour donner envie de lire..."/></label><label>Contenu <small>Séparez vos paragraphes par une ligne vide.</small><textarea name="body" required rows={12} defaultValue={editing?.body} placeholder="Écrivez votre histoire ici..."/></label><div className="admin-form-grid"><label>Image<select name="image" defaultValue={editing?.image||'/images/dakar-coast.jpg'}>{['dakar-coast','market','fishing','youth','architecture','sport'].map(i=><option key={i} value={`/images/${i}.jpg`}>{i}</option>)}</select></label><label>Statut<select name="status" defaultValue={editing?.status||'published'}><option value="published">Publier</option><option value="draft">Brouillon</option></select></label></div><button className="admin-primary" disabled={saving}><Check size={17}/>{saving?'Enregistrement…':editing?'Enregistrer les modifications':'Créer l’article'}</button></form></div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ARTICLE</th><th>RUBRIQUE</th><th>STATUT</th><th>DATE</th><th>ACTIONS</th></tr></thead><tbody>{state.articles.map(a=><tr key={a.id}><td><strong>{a.title}</strong><small>par {a.author}</small></td><td>{categories.find(c=>c.slug===a.category)?.name||a.category}</td><td><span className={`status-pill ${a.status}`}>{a.status==='published'?'Publié':'Brouillon'}</span></td><td>{new Date(a.publishedAt).toLocaleDateString('fr-FR')}</td><td className="admin-actions"><button title="Modifier" onClick={()=>{setEditing(a);setForm('article');window.scrollTo(0,0)}}><PenLine size={17}/></button><button title="Supprimer" onClick={()=>remove('articles',a.id)}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}</>}
 {tab==='journalists'&&<><div className="admin-heading"><div><span className="admin-kicker">ÉQUIPE / JOURNALISTES</span><h1>La rédaction<span>.</span></h1><p>Les signatures qui donnent vie au média.</p></div><button className="admin-primary" onClick={()=>setForm('journalist')}><Plus size={17}/> Ajouter un journaliste</button></div>{form==='journalist'&&<div className="admin-form-panel"><div className="admin-section-head"><h2>Nouveau journaliste</h2><button onClick={()=>setForm(null)}><X size={17}/></button></div><form className="admin-form" onSubmit={e=>submit(e,'journalists')}><label>Nom<input name="name" required/></label><label>Fonction<input name="role" required/></label><label>Présentation<textarea name="bio" rows={3}/></label><button className="admin-primary" disabled={saving}>Ajouter</button></form></div>}<div className="admin-cards">{state.journalists.map(j=><div className="admin-person" key={j.id}><span>{j.initials}</span><div><strong>{j.name}</strong><small>{j.role}</small><p>{j.bio}</p></div><button onClick={()=>remove('journalists',j.id)} aria-label={`Supprimer ${j.name}`}><Trash2 size={17}/></button></div>)}</div></>}
 {tab==='users'&&<><div className="admin-heading"><div><span className="admin-kicker">ÉQUIPE / ANNUAIRE</span><h1>Utilisateurs<span>.</span></h1><p>Un annuaire interne. Les accès restent gérés par le mot de passe administrateur commun.</p></div><button className="admin-primary" onClick={()=>setForm('user')}><Plus size={17}/> Ajouter</button></div>{form==='user'&&<div className="admin-form-panel"><div className="admin-section-head"><h2>Nouvelle fiche</h2><button onClick={()=>setForm(null)}><X size={17}/></button></div><form className="admin-form" onSubmit={e=>submit(e,'users')}><label>Nom<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Rôle<input name="role" placeholder="Rédacteur"/></label><button className="admin-primary" disabled={saving}>Ajouter</button></form></div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>NOM</th><th>E-MAIL</th><th>RÔLE</th><th>ACTIONS</th></tr></thead><tbody>{state.users.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{u.role}</td><td className="admin-actions"><button onClick={()=>remove('users',u.id)} aria-label={`Supprimer ${u.name}`}><Trash2 size={17}/></button></td></tr>)}</tbody></table>{state.users.length===0&&<div className="admin-empty">Aucune fiche utilisateur.</div>}</div></>}
 {tab==='comments'&&<><div className="admin-heading"><div><span className="admin-kicker">COMMUNAUTÉ / MODÉRATION</span><h1>Commentaires<span>.</span></h1><p>{pending} commentaire{pending>1?'s':''} en attente de modération.</p></div></div><div className="admin-comment-list">{state.comments.map(c=><div className="admin-comment" key={c.id}><div><strong>{c.name}</strong><span>{c.email} · {new Date(c.createdAt).toLocaleDateString('fr-FR')}</span><p>{c.body}</p><small>Sur : {state.articles.find(a=>a.id===c.articleId)?.title||'Article supprimé'}</small></div><div className="admin-comment-actions"><span className={`status-pill ${c.approved?'published':'draft'}`}>{c.approved?'Approuvé':'En attente'}</span><button onClick={()=>request('comments','PATCH',{id:c.id,approved:!c.approved})}>{c.approved?'Masquer':'Approuver'}</button><button onClick={()=>remove('comments',c.id)} aria-label="Supprimer"><Trash2 size={16}/></button></div></div>)}{!state.comments.length&&<div className="admin-empty">Aucun commentaire pour le moment.</div>}</div></>}
 {tab==='subscribers'&&<><div className="admin-heading"><div><span className="admin-kicker">AUDIENCE / NEWSLETTER</span><h1>Abonnés<span>.</span></h1><p>{state.subscribers.length} personne{state.subscribers.length>1?'s':''} inscrite{state.subscribers.length>1?'s':''} à la newsletter.</p></div><a className="admin-primary" href="/api/admin/subscribers?format=csv" download><Download size={17}/> Exporter CSV</a></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>E-MAIL</th><th>INSCRIPTION</th><th>ACTIONS</th></tr></thead><tbody>{state.subscribers.map(s=><tr key={s.id}><td><strong>{s.email}</strong></td><td>{new Date(s.createdAt).toLocaleDateString('fr-FR')}</td><td className="admin-actions"><button onClick={()=>remove('subscribers',s.id)} aria-label={`Supprimer ${s.email}`}><Trash2 size={17}/></button></td></tr>)}</tbody></table>{!state.subscribers.length&&<div className="admin-empty">Pas encore d’abonnés.</div>}</div></>}
 {tab==='messages'&&<><div className="admin-heading"><div><span className="admin-kicker">COMMUNAUTÉ / CONTACT</span><h1>Messages<span>.</span></h1><p>Les messages reçus depuis le formulaire de contact.</p></div></div><div className="admin-comment-list">{state.messages.map(m=><div className="admin-comment" key={m.id}><div><strong>{m.subject}</strong><span>{m.name} · {m.email} · {new Date(m.createdAt).toLocaleDateString('fr-FR')}</span><p>{m.message}</p></div><div className="admin-comment-actions"><button onClick={()=>remove('messages',m.id)} aria-label="Supprimer"><Trash2 size={17}/></button></div></div>)}{!state.messages.length&&<div className="admin-empty">Aucun message pour le moment.</div>}</div></>}
 </>}</div></main></div>
}
