import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, Clock3 } from 'lucide-react';
import { categoryName, formatDate } from '@/lib/content';
import type { Article } from '@/lib/types';
export function Eyebrow({children,number}:{children:React.ReactNode,number?:string}){return <div className="section-eyebrow"><span className="eyebrow-square"/>{children}{number&&<span className="eyebrow-number"> / {number}</span>}</div>}
export function SectionHeading({kicker,title,href,linkText='Tout voir'}:{kicker:string,title:string,href?:string,linkText?:string}){return <div className="section-heading"><div><Eyebrow>{kicker}</Eyebrow><h2>{title}</h2></div>{href&&<Link href={href} className="text-link">{linkText}<ArrowUpRight size={17}/></Link>}</div>}
export function ArticleCard({article,variant='standard'}:{article:Article,variant?:'standard'|'horizontal'|'compact'}){return <article className={`article-card card-${variant}`}><Link href={`/article/${article.slug}`} className="card-image"><Image src={article.image} alt="" fill sizes={variant==='horizontal'?'(max-width: 700px) 100vw, 240px':'(max-width: 700px) 100vw, 400px'} /><span className="image-arrow"><ArrowUpRight size={17}/></span></Link><div className="card-copy"><Link href={`/rubrique/${article.category}`} className="category-label">{categoryName(article.category)}</Link><h3><Link href={`/article/${article.slug}`}>{article.title}</Link></h3>{variant!=='compact'&&<p>{article.excerpt}</p>}<div className="card-meta"><span>{article.author}</span><span className="meta-separator"/><span>{formatDate(article.publishedAt)}</span></div></div></article>}
export function FeaturedStory({article}:{article:Article}){return <article className="featured-story"><Link href={`/article/${article.slug}`} className="featured-photo"><Image src={article.image} alt="Vue de Dakar au coucher du soleil" fill priority sizes="(max-width: 800px) 100vw, 65vw"/></Link><div className="featured-overlay"><Link className="featured-category" href={`/rubrique/${article.category}`}><span className="eyebrow-square"/>{categoryName(article.category)} <span> / À LA UNE</span></Link><h1><Link href={`/article/${article.slug}`}>{article.title}</Link></h1><p>{article.excerpt}</p><div className="featured-bottom"><span>PAR {article.author.toUpperCase()} <i/> {formatDate(article.publishedAt).toUpperCase()}</span><Link href={`/article/${article.slug}`} aria-label={`Lire ${article.title}`} className="featured-button"><ArrowRight size={22}/></Link></div></div></article>}
export function StoryRow({article,index}:{article:Article,index:number}){return <article className="story-row"><span className="story-number">{String(index).padStart(2,'0')}</span><div><Link className="category-label" href={`/rubrique/${article.category}`}>{categoryName(article.category)}</Link><h3><Link href={`/article/${article.slug}`}>{article.title}</Link></h3><span className="story-date">{formatDate(article.publishedAt)} · {article.readingTime} min de lecture</span></div><Link href={`/article/${article.slug}`} aria-label={`Lire ${article.title}`} className="story-arrow"><ArrowUpRight size={18}/></Link></article>}
export function ReadingMeta({article}:{article:Article}){return <div className="reading-meta"><span>{formatDate(article.publishedAt)}</span><span><Clock3 size={14}/>{article.readingTime} min de lecture</span></div>}
