'use client';
import { useState, type FormEvent } from 'react';
import { ArrowRight, Check, Send } from 'lucide-react';
export function NewsletterForm({dark=false}:{dark?:boolean}){
 const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{const res=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await res.json();setMessage(data.message||data.error);if(res.ok)setEmail('');}catch{setMessage('Une erreur est survenue. Réessayez.')}finally{setLoading(false)}}
 return <form onSubmit={submit} className={`newsletter-form ${dark?'form-dark':''}`}><div className="form-input-wrap"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Votre adresse e-mail" aria-label="Votre adresse e-mail"/><button disabled={loading} type="submit" aria-label="S'inscrire à la newsletter"><ArrowRight size={21}/></button></div>{message&&<p className="form-message" role="status"><Check size={15}/>{message}</p>}</form>;
}
export function ContactForm(){const [message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const json=await res.json();setMessage(json.message||json.error);if(res.ok)form.reset();}catch{setMessage('Une erreur est survenue. Réessayez.')}finally{setLoading(false)}}
 return <form className="contact-form" onSubmit={submit}><div className="form-grid"><label>Votre nom<input required name="name" placeholder="Votre nom complet" maxLength={80}/></label><label>Votre e-mail<input required type="email" name="email" placeholder="vous@exemple.com"/></label></div><label>Sujet<input required name="subject" placeholder="De quoi souhaitez-vous nous parler ?" maxLength={120}/></label><label>Votre message<textarea required name="message" rows={6} minLength={10} placeholder="Écrivez votre message ici..."/></label><button className="button button-accent" disabled={loading}>{loading?'Envoi en cours...':'Envoyer le message'} <Send size={17}/></button>{message&&<p className="form-message" role="status">{message}</p>}</form>}
export function CommentBox({articleId}:{articleId:string}){const [message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage('');const form=e.currentTarget;const data={...Object.fromEntries(new FormData(form)),articleId};try{const res=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const json=await res.json();setMessage(json.message||json.error);if(res.ok)form.reset();}catch{setMessage('Une erreur est survenue.')}finally{setLoading(false)}}
 return <form className="comment-form" onSubmit={submit}><h3>Participer à la conversation</h3><p>Votre commentaire sera publié après modération.</p><div className="form-grid"><input required name="name" placeholder="Votre nom" maxLength={80} aria-label="Votre nom"/><input required type="email" name="email" placeholder="Votre e-mail (non publié)" aria-label="Votre e-mail"/></div><textarea required name="body" rows={4} minLength={3} maxLength={2000} placeholder="Votre commentaire..." aria-label="Votre commentaire"/><button className="button button-dark" disabled={loading}>Publier un commentaire <ArrowRight size={17}/></button>{message&&<p className="form-message" role="status">{message}</p>}</form>}
export function ShareButtons({title}:{title:string}){const [copied,setCopied]=useState(false);function copy(){navigator.clipboard.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),2500)}return <div className="share-buttons"><span>PARTAGER</span><a target="_blank" rel="noopener noreferrer" href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(typeof window==='undefined'?'':window.location.href)}`} onClick={e=>{e.currentTarget.href=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}`}}>f</a><a target="_blank" rel="noopener noreferrer" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}`} onClick={e=>{e.currentTarget.href=`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(window.location.href)}`}}>𝕏</a><button onClick={copy} type="button">{copied?'✓':'↗'}</button></div>}
